exclude: (^.*patches|.*\.cgi$|^packages/micropip/src/micropip/externals|^benchmark/benchmarks$)
default_language_version:
  python: "3.11"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
        exclude: .clang-format
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.254"
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v15.0.7"
    hooks:
      - id: clang-format
        types_or: [c++, c, cuda]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: "v0.9.0.2"
    hooks:
      - id: shellcheck

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.4"
    hooks:
      - id: codespell

ci:
  autoupdate_schedule: "quarterly"
